#!/usr/bin/env ruby

#require 'texico'
# require 'fileutils'
# require 'slop'
# require 'pastel'
# require 'tty-prompt'

require 'texico'



# Notes:
# - Use 🌮 somewhere/everywhere
#

parser  = Texico::CLI::ArgParser.new
command = parser.parse

command.run
